Cripto/force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Carteira Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Ordem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Ordem__c/fields/Carteira__c.field-meta.xml
<CustomField>
    <fullName>Carteira__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carteira</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>OrdensCarteira</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da execução da ordem.</description>
    <inlineHelpText>Status da execução da ordem.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com lucro</fullName>
            </value>
            <value>
                <fullName>Venda com prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cripto/force-app/main/default/classes/OrdemController.cls
public with sharing class OrdemController {
    @AuraEnabled(cacheable=true)
    public static List<Mercado__c> getMercados(){
        List<Mercado__c> mercado = [select Id, Name from Mercado__c WITH SECURITY_ENFORCED];
        return mercado;
    }

    @AuraEnabled(cacheable=true)
    public static List<Carteira__c> getCarteiras(){
        List<Carteira__c> carteiras =  [select Id, Name from Carteira__c WITH SECURITY_ENFORCED];
        return carteiras;
    }

    @AuraEnabled(cacheable=true)
    public static List<RecordType> getOrdemType(){
        List<RecordType> tipoOrdem = [select Id,Name from RecordType where sObjectType='Ordem__c'];
        return tipoOrdem;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getStatusOptions(){
        List<String> pickListValuesList= new List<String>();
         Schema.DescribeFieldResult fieldResult = Ordem__c.Status__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry pickListVal : ple){
             pickListValuesList.add(pickListVal.getLabel());
         }     
         return pickListValuesList;
     }
}