Cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Mercado__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Significa que o mercado está ativo para novas ordens.</description>
    <inlineHelpText>Significa que o mercado está ativo para novas ordens.</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

Cripto/force-app/main/default/objects/Mercado__c/fields/ContinuousName__c.field-meta.xml
<CustomField>
    <fullName>ContinuousName__c</fullName>
    <description>Nome sem barra</description>
    <formula>SUBSTITUTE(Name  , &quot;/&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContinuousName</label>
    <type>Text</type>
</CustomField>

Cripto/force-app/main/default/objects/Mercado__c/fields/CotacaoAtual__c.field-meta.xml
<CustomField>
    <fullName>CotacaoAtual__c</fullName>
    <label>Cotação atual</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Cripto/force-app/main/default/classes/SchedulerGetPrecoHelper.cls
public with sharing class SchedulerGetPrecoHelper {
    public SchedulerGetPrecoHelper() {

    }

    @Future(Callout=true)
    public static void atualizaCotacaoAtualTodosMercadosAtivos(){
        Map<String, double> priceMap = new Map<String, double>();
        List<BinanceApi.SymbolPrice> spList = BinanceAPI.getPrice();
        
        for(BinanceApi.SymbolPrice sp : spList){
            priceMap.put(sp.symbol, Double.valueof(sp.price));
        }
        List<Mercado__c> mercadoList= [select name, ContinuousName__c FROM Mercado__c where Ativo__c = TRUE and ContinuousName__c in :priceMap.keySet()];

        for(Mercado__c merc : mercadoList){
            merc.CotacaoAtual__c = priceMap.get(merc.ContinuousName__c);
        }
        update mercadoList;
    }
}