Cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Mercado__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Significa que o mercado está ativo para novas ordens.</description>
    <inlineHelpText>Significa que o mercado está ativo para novas ordens.</inlineHelpText>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

Cripto/force-app/main/default/objects/Mercado__c/fields/ContinuousName__c.field-meta.xml
<CustomField>
    <fullName>ContinuousName__c</fullName>
    <description>Nome sem barra</description>
    <formula>SUBSTITUTE(Name  , &quot;/&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContinuousName</label>
    <type>Text</type>
</CustomField>

Cripto/force-app/main/default/objects/Mercado__c/fields/MoedaPrimaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaPrimaria__c</fullName>
    <description>Ativo primário, aquele que é comprado nas operações deste mercado.</description>
    <formula>LEFT(Name, FIND(&quot;/&quot;, Name) -1)</formula>
    <inlineHelpText>Ativo primário, aquele que é comprado nas operações deste mercado.</inlineHelpText>
    <label>Moeda Primária</label>
    <type>Text</type>
</CustomField>

Cripto/force-app/main/default/objects/Mercado__c/fields/MoedaSecundaria__c.field-meta.xml
<CustomField>
    <fullName>MoedaSecundaria__c</fullName>
    <description>Moeda secundário, é o ativo a qual se vende.</description>
    <formula>RIGHT (Name, LEN(Name) -(FIND(&quot;/&quot;, Name) ))</formula>
    <inlineHelpText>Moeda secundário, é o ativo a qual se vende.</inlineHelpText>
    <label>Moeda Secundária</label>
    <type>Text</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Ordem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cripto/force-app/main/default/classes/BinanceAPI.cls
public with sharing class BinanceAPI {

    @Future(Callout=true)
    public static void updatePrices(){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.binance.com/api/v3/ticker/price');
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        List<SymbolPrice> spList = new List<SymbolPrice>();

        if (response.getStatusCode() == 200) {
            spList = (List<SymbolPrice>)JSON.deserialize(response.getBody(), List<SymbolPrice>.class);
        }

        Map<String,  Double> priceMap = new Map<String, Double>();
        
        for(BinanceApi.SymbolPrice sp : spList){
            priceMap.put(sp.symbol, Double.valueof(sp.price));
        }
        List<Mercado__c> mercadoList= [select Id,ContinuousName__c FROM Mercado__c where Ativo__c = TRUE and ContinuousName__c in :priceMap.keySet()];
        List<HistoricoDePreco__c> histPreco = new List<HistoricoDePreco__c>();

        for(Mercado__c merc : mercadoList){
            histPreco.add(new HistoricoDePreco__c(
                Mercado__c = merc.Id,
                Preco__c = priceMap.get(merc.ContinuousName__c)
            ));
            
        }
        insert histPreco;
    }

    @AuraEnabled
    public static List<SymbolPrice> getPrice(){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.binance.com/api/v3/ticker/price');
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            List<SymbolPrice> spList = (List<SymbolPrice>)JSON.deserialize(response.getBody(), List<SymbolPrice>.class);
            return spList;
        }else{
            return null;
        }
    }

    @AuraEnabled
    public static String getPrice(String mercadoId){
        Mercado__c mercado = [SELECT Id, MoedaPrimaria__c, MoedaSecundaria__c 
                              FROM Mercado__c
                              WHERE Id = :mercadoId];

        String pair = mercado.MoedaPrimaria__c + mercado.MoedaSecundaria__c;
        pair = pair.replace('USD', 'USDT');

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://api.binance.com/api/v3/ticker/price?symbol=' + pair);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            SymbolPrice sp = (SymbolPrice)JSON.deserialize(response.getBody(), SymbolPrice.class);
            return sp.price;
        }else{
            return 'Erro ao acessar a API da Binance!';
        }
    }

    public Class SymbolPrice{
        public String symbol {get; set;}
        public String price {get; set;}
    }

    @AuraEnabled
    public static String getRecordTypeId(String ordemType){
        Id rTypeId = Schema.SObjectType.Ordem__c.getRecordTypeInfosByDeveloperName().get(ordemType).getRecordTypeId();
        return rTypeId;
    }
}