Cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Mercado__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <summarizedField>Ordem__c.Quantidade__c</summarizedField>
    <summaryForeignKey>Ordem__c.Mercado__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Ordem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/fields/OperacaoMercado__c.field-meta.xml
<CustomField>
    <fullName>OperacaoMercado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Operação a Mercado?</label>
    <type>Checkbox</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da execução da ordem.</description>
    <inlineHelpText>Status da execução da ordem.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com lucro</fullName>
            </value>
            <value>
                <fullName>Venda com prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Identifica se a ordem é de compra ou venda.</description>
    <inlineHelpText>Identifica se a ordem é de compra ou venda.</inlineHelpText>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compra</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/fields/Validade__c.field-meta.xml
<CustomField>
    <fullName>Validade__c</fullName>
    <label>Validade</label>
    <type>DateTime</type>
</CustomField>

Cripto/force-app/main/default/classes/VFOrdemControlelr.cls
public class VFOrdemControlelr {

    public List<Ordem__c> ordemList {get; set;}

    public String currentValue {get; set;}

    public List<BinanceAPI.SymbolPrice> priceList {get; set;}
    public Date currentDate {get; set;}

    public VFOrdemControlelr(){

    }

    public VFOrdemControlelr(ApexPages.StandardController controller){
        Mercado__c mercado = (Mercado__c) controller.getRecord();

        this.ordemList = [SELECT Id, Name, OperacaoMercado__c, Tipo__c, Status__c, Quantidade__c, Total__c, Validade__c, Preco__c from Ordem__c where Mercado__c = :mercado.Id];

        for(Ordem__c o : ordemList) {
            o.Quantidade__c = o.Quantidade__c.setScale(6);
            o.Preco__c = o.Preco__c.setScale(6);
            o.Total__c = o.Total__c.setScale(6);
        }

        this.currentValue = BinanceAPI.getPrice(mercado.Id);

        this.priceList = BinanceAPI.getPrice();

        currentDate = Date.today();

    }
}