Cripto/force-app/main/default/objects/Mercado__c/Mercado__c.object-meta.xml
<CustomObject>
    <description>Trata-se de um mercado composto por dois ativos onde se pode fazer um investimento trocando um ativo por outro.</description>
    <label>Mercado</label>
    <nameField>
        <label>Mercado Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Mercado__c/fields/CotacaoAtual__c.field-meta.xml
<CustomField>
    <fullName>CotacaoAtual__c</fullName>
    <label>Cotação atual</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/Ordem__c.object-meta.xml
<CustomObject>
    <description>Requisição de uma transação de compra ou venda a serem realizadas em um preço específico.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ORD-{000000}-{DD}/{MM}/{YYYY}</displayFormat>
        <label>Ordem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cripto/force-app/main/default/objects/Ordem__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Mercado__c.Ativo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Mercado__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Cripto/force-app/main/default/objects/Ordem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da execução da ordem.</description>
    <inlineHelpText>Status da execução da ordem.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando</fullName>
                <default>true</default>
                <label>Aguardando</label>
            </value>
            <value>
                <fullName>Executada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Venda com lucro</fullName>
            </value>
            <value>
                <fullName>Venda com prejuízo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Cripto/force-app/main/default/classes/MercadoTriggerHandler.cls
public with sharing class MercadoTriggerHandler extends TriggerHandler{
    public MercadoTriggerHandler() {

    }

    public override void afterUpdate(){
        List<Mercado__c> mercados = trigger.new;
        List<Ordem__c> ordensToUpdate = new List<Ordem__c>();

        List<Mercado__c> mercadoTriggerList = [select Id, CotacaoAtual__c, (select Id, Preco__c, Mercado__c from Ordens__r 
        where status__c = 'Aguardando') from Mercado__c where Id in :Trigger.newMap.keySet()];

        //List<Ordem__c> ordens = [select Id, Name from Ordem__c where Id in :mercadosId and Status__c = 'Aguardando'];
        
        for(Mercado__c mercado : mercadoTriggerList){
            for(Ordem__c ordem : mercado.Ordens__r){
                if(ordem.Mercado__c == mercado.Id)
                {
                    double precoAntigo = this.getPrecoAntigo(mercado.Id);
                    double precoOrdem = ordem.preco__c;
                    double preconovo = mercado.CotacaoAtual__c;
                    if((precoOrdem >=precoAntigo && precoOrdem<= preconovo) || (precoOrdem <=precoAntigo && precoOrdem >= preconovo))
                    {
                        ordensToUpdate.add(new Ordem__c(Id = ordem.Id, Status__c = 'Executada'));
                    }
                }
            }
        }

        update ordensToUpdate;
    }

    public double getPrecoAntigo(String mercadoId){
        Mercado__c mercado = (Mercado__c) Trigger.oldMap.get(mercadoId);
        return mercado.CotacaoAtual__c;
    }
}